// Code generated by cmd/reset
package storage

func (ms *MemStorage) Reset() {
	if ms == nil {
		return
	}
	if ms.GaugeMap != nil {
		clear(ms.GaugeMap)
	}
	if ms.CounterMap != nil {
		clear(ms.CounterMap)
	}
}

