// Code generated by cmd/reset
package storage

func (m *MemStorage) Reset() {
	if m == nil {
		return
	}
	if m.GaugeMap != nil {
		clear(m.GaugeMap)
	}
	if m.CounterMap != nil {
		clear(m.CounterMap)
	}
}

