// Code generated by cmd/reset
package monitors

func (g *gopsutilMonitor) Reset() {
	if g == nil {
		return
	}
	// skip storage.Storage
	// skip sender.Sender
}

func (r *runtimeMonitor) Reset() {
	if r == nil {
		return
	}
	// skip storage.Storage
	// skip sender.Sender
}

